# Generated by Django 5.2.10 on 2026-01-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_pagination_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('id',)},
        ),
    ]
